/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 136
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 92
#define ALIAS_COUNT 10
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 22
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  aux_sym_string_token1 = 3,
  aux_sym_string_token2 = 4,
  aux_sym_string_token3 = 5,
  aux_sym_string_token4 = 6,
  aux_sym_string_token5 = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_let = 10,
  anon_sym_set = 11,
  anon_sym_EQ = 12,
  anon_sym_LPAREN = 13,
  anon_sym_COMMA = 14,
  anon_sym_RPAREN = 15,
  anon_sym_room = 16,
  anon_sym_LBRACE = 17,
  anon_sym_RBRACE = 18,
  anon_sym_name = 19,
  anon_sym_desc = 20,
  anon_sym_description = 21,
  anon_sym_visited = 22,
  anon_sym_exit = 23,
  anon_sym_DASH_GT = 24,
  anon_sym_required_items = 25,
  anon_sym_required_flags = 26,
  anon_sym_barred = 27,
  anon_sym_overlay = 28,
  anon_sym_if = 29,
  anon_sym_text = 30,
  anon_sym_flag = 31,
  anon_sym_unset = 32,
  anon_sym_complete = 33,
  anon_sym_item = 34,
  anon_sym_present = 35,
  anon_sym_absent = 36,
  anon_sym_npc = 37,
  anon_sym_trigger = 38,
  anon_sym_spinner = 39,
  anon_sym_goal = 40,
  sym_source_file = 41,
  sym_string = 42,
  sym_boolean = 43,
  sym_set_decl = 44,
  sym_set_list = 45,
  sym_room_def = 46,
  sym_room_block = 47,
  sym_room_stmt = 48,
  sym_room_name = 49,
  sym_room_desc = 50,
  sym_room_visited = 51,
  sym_room_exit = 52,
  sym_exit_block = 53,
  sym_exit_stmt = 54,
  sym_required_items_stmt = 55,
  sym_required_flags_stmt = 56,
  sym_barred_stmt = 57,
  sym_overlay_stmt = 58,
  sym_ovl_block = 59,
  sym_ovl_text_stmt = 60,
  sym_ovl_cond_list = 61,
  sym_ovl_cond = 62,
  sym_ovl_flag_status = 63,
  sym_ovl_item_presence = 64,
  sym_item_def = 65,
  sym_item_block = 66,
  sym_item_stmt = 67,
  sym_npc_def = 68,
  sym_npc_block = 69,
  sym_npc_stmt = 70,
  sym_trigger_def = 71,
  sym_trigger_block = 72,
  sym_trigger_stmt = 73,
  sym_spinner_def = 74,
  sym_spinner_block = 75,
  sym_spinner_stmt = 76,
  sym_goal_def = 77,
  sym_goal_block = 78,
  sym_goal_stmt = 79,
  aux_sym_source_file_repeat1 = 80,
  aux_sym_set_list_repeat1 = 81,
  aux_sym_room_block_repeat1 = 82,
  aux_sym_exit_block_repeat1 = 83,
  aux_sym_required_items_stmt_repeat1 = 84,
  aux_sym_required_flags_stmt_repeat1 = 85,
  aux_sym_ovl_cond_list_repeat1 = 86,
  aux_sym_item_block_repeat1 = 87,
  aux_sym_npc_block_repeat1 = 88,
  aux_sym_trigger_block_repeat1 = 89,
  aux_sym_spinner_block_repeat1 = 90,
  aux_sym_goal_block_repeat1 = 91,
  alias_sym_barred_msg = 92,
  alias_sym_exit_dest = 93,
  alias_sym_exit_dir = 94,
  alias_sym_goal_id = 95,
  alias_sym_item_id = 96,
  alias_sym_npc_id = 97,
  alias_sym_ovl_text = 98,
  alias_sym_room_id = 99,
  alias_sym_spinner_name = 100,
  alias_sym_trigger_name = 101,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [aux_sym_string_token3] = "string_token3",
  [aux_sym_string_token4] = "string_token4",
  [aux_sym_string_token5] = "string_token5",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_let] = "let",
  [anon_sym_set] = "set",
  [anon_sym_EQ] = "=",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_room] = "room",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_name] = "name",
  [anon_sym_desc] = "desc",
  [anon_sym_description] = "description",
  [anon_sym_visited] = "visited",
  [anon_sym_exit] = "exit",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_required_items] = "required_items",
  [anon_sym_required_flags] = "required_flags",
  [anon_sym_barred] = "barred",
  [anon_sym_overlay] = "overlay",
  [anon_sym_if] = "if",
  [anon_sym_text] = "text",
  [anon_sym_flag] = "flag",
  [anon_sym_unset] = "unset",
  [anon_sym_complete] = "complete",
  [anon_sym_item] = "item",
  [anon_sym_present] = "present",
  [anon_sym_absent] = "absent",
  [anon_sym_npc] = "npc",
  [anon_sym_trigger] = "trigger",
  [anon_sym_spinner] = "spinner",
  [anon_sym_goal] = "goal",
  [sym_source_file] = "source_file",
  [sym_string] = "room_desc",
  [sym_boolean] = "room_visited",
  [sym_set_decl] = "set_decl",
  [sym_set_list] = "set_list",
  [sym_room_def] = "room_def",
  [sym_room_block] = "room_block",
  [sym_room_stmt] = "room_stmt",
  [sym_room_name] = "room_name",
  [sym_room_desc] = "room_desc",
  [sym_room_visited] = "room_visited",
  [sym_room_exit] = "room_exit",
  [sym_exit_block] = "exit_block",
  [sym_exit_stmt] = "exit_stmt",
  [sym_required_items_stmt] = "required_items_stmt",
  [sym_required_flags_stmt] = "required_flags_stmt",
  [sym_barred_stmt] = "barred_stmt",
  [sym_overlay_stmt] = "overlay_stmt",
  [sym_ovl_block] = "ovl_block",
  [sym_ovl_text_stmt] = "ovl_text_stmt",
  [sym_ovl_cond_list] = "ovl_cond_list",
  [sym_ovl_cond] = "ovl_cond",
  [sym_ovl_flag_status] = "ovl_flag_status",
  [sym_ovl_item_presence] = "ovl_item_presence",
  [sym_item_def] = "item_def",
  [sym_item_block] = "item_block",
  [sym_item_stmt] = "item_stmt",
  [sym_npc_def] = "npc_def",
  [sym_npc_block] = "npc_block",
  [sym_npc_stmt] = "npc_stmt",
  [sym_trigger_def] = "trigger_def",
  [sym_trigger_block] = "trigger_block",
  [sym_trigger_stmt] = "trigger_stmt",
  [sym_spinner_def] = "spinner_def",
  [sym_spinner_block] = "spinner_block",
  [sym_spinner_stmt] = "spinner_stmt",
  [sym_goal_def] = "goal_def",
  [sym_goal_block] = "goal_block",
  [sym_goal_stmt] = "goal_stmt",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_set_list_repeat1] = "set_list_repeat1",
  [aux_sym_room_block_repeat1] = "room_block_repeat1",
  [aux_sym_exit_block_repeat1] = "exit_block_repeat1",
  [aux_sym_required_items_stmt_repeat1] = "required_items_stmt_repeat1",
  [aux_sym_required_flags_stmt_repeat1] = "required_flags_stmt_repeat1",
  [aux_sym_ovl_cond_list_repeat1] = "ovl_cond_list_repeat1",
  [aux_sym_item_block_repeat1] = "item_block_repeat1",
  [aux_sym_npc_block_repeat1] = "npc_block_repeat1",
  [aux_sym_trigger_block_repeat1] = "trigger_block_repeat1",
  [aux_sym_spinner_block_repeat1] = "spinner_block_repeat1",
  [aux_sym_goal_block_repeat1] = "goal_block_repeat1",
  [alias_sym_barred_msg] = "barred_msg",
  [alias_sym_exit_dest] = "exit_dest",
  [alias_sym_exit_dir] = "exit_dir",
  [alias_sym_goal_id] = "goal_id",
  [alias_sym_item_id] = "item_id",
  [alias_sym_npc_id] = "npc_id",
  [alias_sym_ovl_text] = "ovl_text",
  [alias_sym_room_id] = "room_id",
  [alias_sym_spinner_name] = "spinner_name",
  [alias_sym_trigger_name] = "trigger_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [aux_sym_string_token3] = aux_sym_string_token3,
  [aux_sym_string_token4] = aux_sym_string_token4,
  [aux_sym_string_token5] = aux_sym_string_token5,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_room] = anon_sym_room,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_name] = anon_sym_name,
  [anon_sym_desc] = anon_sym_desc,
  [anon_sym_description] = anon_sym_description,
  [anon_sym_visited] = anon_sym_visited,
  [anon_sym_exit] = anon_sym_exit,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_required_items] = anon_sym_required_items,
  [anon_sym_required_flags] = anon_sym_required_flags,
  [anon_sym_barred] = anon_sym_barred,
  [anon_sym_overlay] = anon_sym_overlay,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_text] = anon_sym_text,
  [anon_sym_flag] = anon_sym_flag,
  [anon_sym_unset] = anon_sym_unset,
  [anon_sym_complete] = anon_sym_complete,
  [anon_sym_item] = anon_sym_item,
  [anon_sym_present] = anon_sym_present,
  [anon_sym_absent] = anon_sym_absent,
  [anon_sym_npc] = anon_sym_npc,
  [anon_sym_trigger] = anon_sym_trigger,
  [anon_sym_spinner] = anon_sym_spinner,
  [anon_sym_goal] = anon_sym_goal,
  [sym_source_file] = sym_source_file,
  [sym_string] = sym_room_desc,
  [sym_boolean] = sym_room_visited,
  [sym_set_decl] = sym_set_decl,
  [sym_set_list] = sym_set_list,
  [sym_room_def] = sym_room_def,
  [sym_room_block] = sym_room_block,
  [sym_room_stmt] = sym_room_stmt,
  [sym_room_name] = sym_room_name,
  [sym_room_desc] = sym_room_desc,
  [sym_room_visited] = sym_room_visited,
  [sym_room_exit] = sym_room_exit,
  [sym_exit_block] = sym_exit_block,
  [sym_exit_stmt] = sym_exit_stmt,
  [sym_required_items_stmt] = sym_required_items_stmt,
  [sym_required_flags_stmt] = sym_required_flags_stmt,
  [sym_barred_stmt] = sym_barred_stmt,
  [sym_overlay_stmt] = sym_overlay_stmt,
  [sym_ovl_block] = sym_ovl_block,
  [sym_ovl_text_stmt] = sym_ovl_text_stmt,
  [sym_ovl_cond_list] = sym_ovl_cond_list,
  [sym_ovl_cond] = sym_ovl_cond,
  [sym_ovl_flag_status] = sym_ovl_flag_status,
  [sym_ovl_item_presence] = sym_ovl_item_presence,
  [sym_item_def] = sym_item_def,
  [sym_item_block] = sym_item_block,
  [sym_item_stmt] = sym_item_stmt,
  [sym_npc_def] = sym_npc_def,
  [sym_npc_block] = sym_npc_block,
  [sym_npc_stmt] = sym_npc_stmt,
  [sym_trigger_def] = sym_trigger_def,
  [sym_trigger_block] = sym_trigger_block,
  [sym_trigger_stmt] = sym_trigger_stmt,
  [sym_spinner_def] = sym_spinner_def,
  [sym_spinner_block] = sym_spinner_block,
  [sym_spinner_stmt] = sym_spinner_stmt,
  [sym_goal_def] = sym_goal_def,
  [sym_goal_block] = sym_goal_block,
  [sym_goal_stmt] = sym_goal_stmt,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_set_list_repeat1] = aux_sym_set_list_repeat1,
  [aux_sym_room_block_repeat1] = aux_sym_room_block_repeat1,
  [aux_sym_exit_block_repeat1] = aux_sym_exit_block_repeat1,
  [aux_sym_required_items_stmt_repeat1] = aux_sym_required_items_stmt_repeat1,
  [aux_sym_required_flags_stmt_repeat1] = aux_sym_required_flags_stmt_repeat1,
  [aux_sym_ovl_cond_list_repeat1] = aux_sym_ovl_cond_list_repeat1,
  [aux_sym_item_block_repeat1] = aux_sym_item_block_repeat1,
  [aux_sym_npc_block_repeat1] = aux_sym_npc_block_repeat1,
  [aux_sym_trigger_block_repeat1] = aux_sym_trigger_block_repeat1,
  [aux_sym_spinner_block_repeat1] = aux_sym_spinner_block_repeat1,
  [aux_sym_goal_block_repeat1] = aux_sym_goal_block_repeat1,
  [alias_sym_barred_msg] = alias_sym_barred_msg,
  [alias_sym_exit_dest] = alias_sym_exit_dest,
  [alias_sym_exit_dir] = alias_sym_exit_dir,
  [alias_sym_goal_id] = alias_sym_goal_id,
  [alias_sym_item_id] = alias_sym_item_id,
  [alias_sym_npc_id] = alias_sym_npc_id,
  [alias_sym_ovl_text] = alias_sym_ovl_text,
  [alias_sym_room_id] = alias_sym_room_id,
  [alias_sym_spinner_name] = alias_sym_spinner_name,
  [alias_sym_trigger_name] = alias_sym_trigger_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token5] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_room] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_name] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_desc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_description] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_visited] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_required_items] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_required_flags] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_barred] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_overlay] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_text] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_complete] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_item] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_present] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_absent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_npc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_trigger] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_spinner] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_goal] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_set_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_set_list] = {
    .visible = true,
    .named = true,
  },
  [sym_room_def] = {
    .visible = true,
    .named = true,
  },
  [sym_room_block] = {
    .visible = true,
    .named = true,
  },
  [sym_room_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_room_name] = {
    .visible = true,
    .named = true,
  },
  [sym_room_desc] = {
    .visible = true,
    .named = true,
  },
  [sym_room_visited] = {
    .visible = true,
    .named = true,
  },
  [sym_room_exit] = {
    .visible = true,
    .named = true,
  },
  [sym_exit_block] = {
    .visible = true,
    .named = true,
  },
  [sym_exit_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_required_items_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_required_flags_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_barred_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_overlay_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_ovl_block] = {
    .visible = true,
    .named = true,
  },
  [sym_ovl_text_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_ovl_cond_list] = {
    .visible = true,
    .named = true,
  },
  [sym_ovl_cond] = {
    .visible = true,
    .named = true,
  },
  [sym_ovl_flag_status] = {
    .visible = true,
    .named = true,
  },
  [sym_ovl_item_presence] = {
    .visible = true,
    .named = true,
  },
  [sym_item_def] = {
    .visible = true,
    .named = true,
  },
  [sym_item_block] = {
    .visible = true,
    .named = true,
  },
  [sym_item_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_npc_def] = {
    .visible = true,
    .named = true,
  },
  [sym_npc_block] = {
    .visible = true,
    .named = true,
  },
  [sym_npc_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger_def] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger_block] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_spinner_def] = {
    .visible = true,
    .named = true,
  },
  [sym_spinner_block] = {
    .visible = true,
    .named = true,
  },
  [sym_spinner_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_goal_def] = {
    .visible = true,
    .named = true,
  },
  [sym_goal_block] = {
    .visible = true,
    .named = true,
  },
  [sym_goal_stmt] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_set_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_room_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exit_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_required_items_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_required_flags_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ovl_cond_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_item_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_npc_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_trigger_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_spinner_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_goal_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_barred_msg] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_exit_dest] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_exit_dir] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_goal_id] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_item_id] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_npc_id] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_ovl_text] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_room_id] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_spinner_name] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_trigger_name] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_desc = 1,
  field_dest = 2,
  field_dir = 3,
  field_flag_id = 4,
  field_flag_name = 5,
  field_id = 6,
  field_item_id = 7,
  field_msg = 8,
  field_name = 9,
  field_text = 10,
  field_visited = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_desc] = "desc",
  [field_dest] = "dest",
  [field_dir] = "dir",
  [field_flag_id] = "flag_id",
  [field_flag_name] = "flag_name",
  [field_id] = "id",
  [field_item_id] = "item_id",
  [field_msg] = "msg",
  [field_name] = "name",
  [field_text] = "text",
  [field_visited] = "visited",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 0, .length = 1},
  [4] = {.index = 1, .length = 1},
  [5] = {.index = 1, .length = 1},
  [6] = {.index = 0, .length = 1},
  [7] = {.index = 1, .length = 1},
  [8] = {.index = 2, .length = 1},
  [9] = {.index = 3, .length = 1},
  [10] = {.index = 4, .length = 2},
  [11] = {.index = 6, .length = 1},
  [12] = {.index = 7, .length = 1},
  [13] = {.index = 8, .length = 1},
  [14] = {.index = 9, .length = 1},
  [15] = {.index = 10, .length = 1},
  [16] = {.index = 11, .length = 1},
  [17] = {.index = 12, .length = 2},
  [18] = {.index = 14, .length = 2},
  [19] = {.index = 16, .length = 1},
  [20] = {.index = 17, .length = 2},
  [21] = {.index = 19, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_id, 1},
  [1] =
    {field_name, 1},
  [2] =
    {field_desc, 1},
  [3] =
    {field_visited, 1},
  [4] =
    {field_dest, 3},
    {field_dir, 1},
  [6] =
    {field_flag_name, 2},
  [7] =
    {field_item_id, 2},
  [8] =
    {field_text, 1},
  [9] =
    {field_msg, 1},
  [10] =
    {field_flag_id, 2},
  [11] =
    {field_item_id, 1},
  [12] =
    {field_item_id, 2},
    {field_item_id, 3, .inherited = true},
  [14] =
    {field_item_id, 0, .inherited = true},
    {field_item_id, 1, .inherited = true},
  [16] =
    {field_flag_id, 1},
  [17] =
    {field_flag_id, 2},
    {field_flag_id, 3, .inherited = true},
  [19] =
    {field_flag_id, 0, .inherited = true},
    {field_flag_id, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_room_id,
  },
  [2] = {
    [1] = alias_sym_item_id,
  },
  [3] = {
    [1] = alias_sym_npc_id,
  },
  [4] = {
    [1] = alias_sym_trigger_name,
  },
  [5] = {
    [1] = alias_sym_spinner_name,
  },
  [6] = {
    [1] = alias_sym_goal_id,
  },
  [7] = {
    [1] = sym_room_name,
  },
  [10] = {
    [1] = alias_sym_exit_dir,
    [3] = alias_sym_exit_dest,
  },
  [13] = {
    [1] = alias_sym_ovl_text,
  },
  [14] = {
    [1] = alias_sym_barred_msg,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_string, 7,
    sym_room_desc,
    alias_sym_barred_msg,
    alias_sym_exit_dir,
    alias_sym_ovl_text,
    alias_sym_spinner_name,
    alias_sym_trigger_name,
    sym_room_name,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 1,
        '#', 25,
        '\'', 12,
        '(', 41,
        ')', 43,
        ',', 42,
        '-', 29,
        '=', 40,
        'r', 28,
        '{', 44,
        '}', 45,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(11);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(36);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 10:
      if (lookahead == '#') ADVANCE(26);
      if (lookahead == '-') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      END_STATE();
    case 11:
      if (lookahead == '#') ADVANCE(39);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 12:
      if (lookahead == '\'') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == '\'') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '\'') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == '\'') ADVANCE(38);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == '\'') ADVANCE(15);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 18:
      if (lookahead == '\'') ADVANCE(16);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 19:
      if (lookahead == '\'') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 20:
      if (lookahead == '>') ADVANCE(46);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead == '\'') ADVANCE(12);
      if (lookahead == '(') ADVANCE(41);
      if (lookahead == 'r') ADVANCE(28);
      if (lookahead == '{') ADVANCE(44);
      if (lookahead == '}') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#') ADVANCE(27);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '>') ADVANCE(46);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '"') ADVANCE(6);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\'') ADVANCE(14);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_string_token3);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '"') ADVANCE(35);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_string_token4);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_token4);
      if (lookahead == '\'') ADVANCE(37);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_token5);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'g', 7,
        'i', 8,
        'l', 9,
        'n', 10,
        'o', 11,
        'p', 12,
        'r', 13,
        's', 14,
        't', 15,
        'u', 16,
        'v', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'b') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'x') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(23);
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(26);
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(29);
      if (lookahead == 'p') ADVANCE(30);
      END_STATE();
    case 11:
      if (lookahead == 'v') ADVANCE(31);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(33);
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(35);
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(37);
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(43);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(45);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(47);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 29:
      if (lookahead == 'm') ADVANCE(51);
      END_STATE();
    case 30:
      if (lookahead == 'c') ADVANCE(52);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 33:
      if (lookahead == 'q') ADVANCE(55);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(56);
      END_STATE();
    case 35:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 37:
      if (lookahead == 'x') ADVANCE(59);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(60);
      if (lookahead == 'u') ADVANCE(61);
      END_STATE();
    case 39:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(65);
      END_STATE();
    case 43:
      if (lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 44:
      if (lookahead == 'c') ADVANCE(67);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(69);
      END_STATE();
    case 47:
      if (lookahead == 'g') ADVANCE(70);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 49:
      if (lookahead == 'm') ADVANCE(72);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 51:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_npc);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(74);
      END_STATE();
    case 54:
      if (lookahead == 's') ADVANCE(75);
      END_STATE();
    case 55:
      if (lookahead == 'u') ADVANCE(76);
      END_STATE();
    case 56:
      if (lookahead == 'm') ADVANCE(77);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(78);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(79);
      END_STATE();
    case 60:
      if (lookahead == 'g') ADVANCE(80);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 63:
      if (lookahead == 'i') ADVANCE(83);
      END_STATE();
    case 64:
      if (lookahead == 'n') ADVANCE(84);
      END_STATE();
    case 65:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 66:
      if (lookahead == 'l') ADVANCE(86);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_desc);
      if (lookahead == 'r') ADVANCE(87);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_exit);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(88);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_flag);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_goal);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_item);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_name);
      END_STATE();
    case 74:
      if (lookahead == 'l') ADVANCE(89);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 76:
      if (lookahead == 'i') ADVANCE(91);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_room);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(92);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_text);
      END_STATE();
    case 80:
      if (lookahead == 'g') ADVANCE(93);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 82:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(95);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(96);
      END_STATE();
    case 85:
      if (lookahead == 'd') ADVANCE(97);
      END_STATE();
    case 86:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 87:
      if (lookahead == 'i') ADVANCE(99);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 89:
      if (lookahead == 'a') ADVANCE(100);
      END_STATE();
    case 90:
      if (lookahead == 'n') ADVANCE(101);
      END_STATE();
    case 91:
      if (lookahead == 'r') ADVANCE(102);
      END_STATE();
    case 92:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 93:
      if (lookahead == 'e') ADVANCE(104);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_unset);
      END_STATE();
    case 95:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_absent);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_barred);
      END_STATE();
    case 98:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 99:
      if (lookahead == 'p') ADVANCE(107);
      END_STATE();
    case 100:
      if (lookahead == 'y') ADVANCE(108);
      END_STATE();
    case 101:
      if (lookahead == 't') ADVANCE(109);
      END_STATE();
    case 102:
      if (lookahead == 'e') ADVANCE(110);
      END_STATE();
    case 103:
      if (lookahead == 'r') ADVANCE(111);
      END_STATE();
    case 104:
      if (lookahead == 'r') ADVANCE(112);
      END_STATE();
    case 105:
      if (lookahead == 'd') ADVANCE(113);
      END_STATE();
    case 106:
      if (lookahead == 'e') ADVANCE(114);
      END_STATE();
    case 107:
      if (lookahead == 't') ADVANCE(115);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_overlay);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_present);
      END_STATE();
    case 110:
      if (lookahead == 'd') ADVANCE(116);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_spinner);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_trigger);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_visited);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_complete);
      END_STATE();
    case 115:
      if (lookahead == 'i') ADVANCE(117);
      END_STATE();
    case 116:
      if (lookahead == '_') ADVANCE(118);
      END_STATE();
    case 117:
      if (lookahead == 'o') ADVANCE(119);
      END_STATE();
    case 118:
      if (lookahead == 'f') ADVANCE(120);
      if (lookahead == 'i') ADVANCE(121);
      END_STATE();
    case 119:
      if (lookahead == 'n') ADVANCE(122);
      END_STATE();
    case 120:
      if (lookahead == 'l') ADVANCE(123);
      END_STATE();
    case 121:
      if (lookahead == 't') ADVANCE(124);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_description);
      END_STATE();
    case 123:
      if (lookahead == 'a') ADVANCE(125);
      END_STATE();
    case 124:
      if (lookahead == 'e') ADVANCE(126);
      END_STATE();
    case 125:
      if (lookahead == 'g') ADVANCE(127);
      END_STATE();
    case 126:
      if (lookahead == 'm') ADVANCE(128);
      END_STATE();
    case 127:
      if (lookahead == 's') ADVANCE(129);
      END_STATE();
    case 128:
      if (lookahead == 's') ADVANCE(130);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_required_flags);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_required_items);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 23},
  [3] = {.lex_state = 23},
  [4] = {.lex_state = 23},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 23},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 23},
  [9] = {.lex_state = 23},
  [10] = {.lex_state = 23},
  [11] = {.lex_state = 23},
  [12] = {.lex_state = 23},
  [13] = {.lex_state = 23},
  [14] = {.lex_state = 23},
  [15] = {.lex_state = 23},
  [16] = {.lex_state = 23},
  [17] = {.lex_state = 23},
  [18] = {.lex_state = 23},
  [19] = {.lex_state = 23},
  [20] = {.lex_state = 23},
  [21] = {.lex_state = 23},
  [22] = {.lex_state = 23},
  [23] = {.lex_state = 23},
  [24] = {.lex_state = 23},
  [25] = {.lex_state = 23},
  [26] = {.lex_state = 23},
  [27] = {.lex_state = 23},
  [28] = {.lex_state = 23},
  [29] = {.lex_state = 23},
  [30] = {.lex_state = 23},
  [31] = {.lex_state = 23},
  [32] = {.lex_state = 23},
  [33] = {.lex_state = 23},
  [34] = {.lex_state = 23},
  [35] = {.lex_state = 23},
  [36] = {.lex_state = 23},
  [37] = {.lex_state = 23},
  [38] = {.lex_state = 23},
  [39] = {.lex_state = 23},
  [40] = {.lex_state = 23},
  [41] = {.lex_state = 23},
  [42] = {.lex_state = 23},
  [43] = {.lex_state = 23},
  [44] = {.lex_state = 23},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 23},
  [52] = {.lex_state = 23},
  [53] = {.lex_state = 23},
  [54] = {.lex_state = 23},
  [55] = {.lex_state = 23},
  [56] = {.lex_state = 23},
  [57] = {.lex_state = 23},
  [58] = {.lex_state = 23},
  [59] = {.lex_state = 23},
  [60] = {.lex_state = 23},
  [61] = {.lex_state = 23},
  [62] = {.lex_state = 23},
  [63] = {.lex_state = 23},
  [64] = {.lex_state = 23},
  [65] = {.lex_state = 23},
  [66] = {.lex_state = 23},
  [67] = {.lex_state = 23},
  [68] = {.lex_state = 23},
  [69] = {.lex_state = 23},
  [70] = {.lex_state = 23},
  [71] = {.lex_state = 23},
  [72] = {.lex_state = 23},
  [73] = {.lex_state = 23},
  [74] = {.lex_state = 23},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 23},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 23},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 23},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 23},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 23},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 23},
  [107] = {.lex_state = 23},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 23},
  [110] = {.lex_state = 23},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 23},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 23},
  [118] = {.lex_state = 23},
  [119] = {.lex_state = 23},
  [120] = {.lex_state = 23},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 10},
  [124] = {.lex_state = 23},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 23},
  [127] = {.lex_state = 23},
  [128] = {.lex_state = 23},
  [129] = {.lex_state = 23},
  [130] = {.lex_state = 23},
  [131] = {.lex_state = 23},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 23},
  [134] = {.lex_state = 23},
  [135] = {.lex_state = 23},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [aux_sym_string_token3] = ACTIONS(1),
    [aux_sym_string_token4] = ACTIONS(1),
    [aux_sym_string_token5] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_room] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_name] = ACTIONS(1),
    [anon_sym_desc] = ACTIONS(1),
    [anon_sym_description] = ACTIONS(1),
    [anon_sym_visited] = ACTIONS(1),
    [anon_sym_exit] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_required_items] = ACTIONS(1),
    [anon_sym_required_flags] = ACTIONS(1),
    [anon_sym_barred] = ACTIONS(1),
    [anon_sym_overlay] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_text] = ACTIONS(1),
    [anon_sym_flag] = ACTIONS(1),
    [anon_sym_unset] = ACTIONS(1),
    [anon_sym_complete] = ACTIONS(1),
    [anon_sym_item] = ACTIONS(1),
    [anon_sym_present] = ACTIONS(1),
    [anon_sym_absent] = ACTIONS(1),
    [anon_sym_npc] = ACTIONS(1),
    [anon_sym_trigger] = ACTIONS(1),
    [anon_sym_spinner] = ACTIONS(1),
    [anon_sym_goal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(132),
    [sym_set_decl] = STATE(2),
    [sym_room_def] = STATE(2),
    [sym_item_def] = STATE(2),
    [sym_npc_def] = STATE(2),
    [sym_trigger_def] = STATE(2),
    [sym_spinner_def] = STATE(2),
    [sym_goal_def] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_room] = ACTIONS(9),
    [anon_sym_item] = ACTIONS(11),
    [anon_sym_npc] = ACTIONS(13),
    [anon_sym_trigger] = ACTIONS(15),
    [anon_sym_spinner] = ACTIONS(17),
    [anon_sym_goal] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_room,
    ACTIONS(11), 1,
      anon_sym_item,
    ACTIONS(13), 1,
      anon_sym_npc,
    ACTIONS(15), 1,
      anon_sym_trigger,
    ACTIONS(17), 1,
      anon_sym_spinner,
    ACTIONS(19), 1,
      anon_sym_goal,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(3), 8,
      sym_set_decl,
      sym_room_def,
      sym_item_def,
      sym_npc_def,
      sym_trigger_def,
      sym_spinner_def,
      sym_goal_def,
      aux_sym_source_file_repeat1,
  [38] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_let,
    ACTIONS(28), 1,
      anon_sym_room,
    ACTIONS(31), 1,
      anon_sym_item,
    ACTIONS(34), 1,
      anon_sym_npc,
    ACTIONS(37), 1,
      anon_sym_trigger,
    ACTIONS(40), 1,
      anon_sym_spinner,
    ACTIONS(43), 1,
      anon_sym_goal,
    STATE(3), 8,
      sym_set_decl,
      sym_room_def,
      sym_item_def,
      sym_npc_def,
      sym_trigger_def,
      sym_spinner_def,
      sym_goal_def,
      aux_sym_source_file_repeat1,
  [76] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    ACTIONS(48), 1,
      anon_sym_name,
    ACTIONS(50), 1,
      anon_sym_desc,
    ACTIONS(52), 1,
      anon_sym_description,
    ACTIONS(54), 1,
      anon_sym_visited,
    ACTIONS(56), 1,
      anon_sym_exit,
    ACTIONS(58), 1,
      anon_sym_overlay,
    STATE(5), 2,
      sym_room_stmt,
      aux_sym_room_block_repeat1,
    STATE(39), 5,
      sym_room_name,
      sym_room_desc,
      sym_room_visited,
      sym_room_exit,
      sym_overlay_stmt,
  [112] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(48), 1,
      anon_sym_name,
    ACTIONS(50), 1,
      anon_sym_desc,
    ACTIONS(52), 1,
      anon_sym_description,
    ACTIONS(54), 1,
      anon_sym_visited,
    ACTIONS(56), 1,
      anon_sym_exit,
    ACTIONS(58), 1,
      anon_sym_overlay,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    STATE(6), 2,
      sym_room_stmt,
      aux_sym_room_block_repeat1,
    STATE(39), 5,
      sym_room_name,
      sym_room_desc,
      sym_room_visited,
      sym_room_exit,
      sym_overlay_stmt,
  [148] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      anon_sym_name,
    ACTIONS(67), 1,
      anon_sym_desc,
    ACTIONS(70), 1,
      anon_sym_description,
    ACTIONS(73), 1,
      anon_sym_visited,
    ACTIONS(76), 1,
      anon_sym_exit,
    ACTIONS(79), 1,
      anon_sym_overlay,
    STATE(6), 2,
      sym_room_stmt,
      aux_sym_room_block_repeat1,
    STATE(39), 5,
      sym_room_name,
      sym_room_desc,
      sym_room_visited,
      sym_room_exit,
      sym_overlay_stmt,
  [184] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_desc,
    ACTIONS(82), 11,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_DASH_GT,
      anon_sym_required_items,
      anon_sym_required_flags,
      anon_sym_barred,
      anon_sym_overlay,
  [204] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(90), 1,
      anon_sym_desc,
    STATE(37), 1,
      sym_exit_block,
    ACTIONS(88), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [225] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    ACTIONS(94), 1,
      anon_sym_required_items,
    ACTIONS(96), 1,
      anon_sym_required_flags,
    ACTIONS(98), 1,
      anon_sym_barred,
    STATE(10), 2,
      sym_exit_stmt,
      aux_sym_exit_block_repeat1,
    STATE(64), 3,
      sym_required_items_stmt,
      sym_required_flags_stmt,
      sym_barred_stmt,
  [250] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_required_items,
    ACTIONS(96), 1,
      anon_sym_required_flags,
    ACTIONS(98), 1,
      anon_sym_barred,
    ACTIONS(100), 1,
      anon_sym_RBRACE,
    STATE(11), 2,
      sym_exit_stmt,
      aux_sym_exit_block_repeat1,
    STATE(64), 3,
      sym_required_items_stmt,
      sym_required_flags_stmt,
      sym_barred_stmt,
  [275] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(104), 1,
      anon_sym_required_items,
    ACTIONS(107), 1,
      anon_sym_required_flags,
    ACTIONS(110), 1,
      anon_sym_barred,
    STATE(11), 2,
      sym_exit_stmt,
      aux_sym_exit_block_repeat1,
    STATE(64), 3,
      sym_required_items_stmt,
      sym_required_flags_stmt,
      sym_barred_stmt,
  [300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [328] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [342] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [356] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [370] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [398] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [412] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [426] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [454] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [468] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [482] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [496] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [510] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [524] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [552] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [566] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [580] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_room,
      anon_sym_item,
      anon_sym_npc,
      anon_sym_trigger,
      anon_sym_spinner,
      anon_sym_goal,
  [594] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      anon_sym_desc,
    ACTIONS(155), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [609] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_desc,
    ACTIONS(159), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [624] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_desc,
    ACTIONS(163), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [639] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_desc,
    ACTIONS(167), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [654] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      anon_sym_desc,
    ACTIONS(171), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [669] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_LPAREN,
    ACTIONS(177), 1,
      anon_sym_flag,
    ACTIONS(179), 1,
      anon_sym_item,
    STATE(108), 1,
      sym_ovl_cond_list,
    STATE(125), 1,
      sym_ovl_cond,
    STATE(84), 2,
      sym_ovl_flag_status,
      sym_ovl_item_presence,
  [692] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_desc,
    ACTIONS(181), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [707] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_desc,
    ACTIONS(185), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [722] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_desc,
    ACTIONS(189), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [737] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_desc,
    ACTIONS(193), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [752] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      sym_identifier,
    STATE(123), 1,
      sym_string,
    ACTIONS(199), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(201), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(205), 1,
      anon_sym_desc,
    ACTIONS(203), 6,
      anon_sym_RBRACE,
      anon_sym_name,
      anon_sym_description,
      anon_sym_visited,
      anon_sym_exit,
      anon_sym_overlay,
  [786] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(101), 1,
      sym_string,
    ACTIONS(199), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(201), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [802] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(33), 1,
      sym_string,
    ACTIONS(199), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(201), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [818] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(53), 1,
      sym_string,
    ACTIONS(199), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(201), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [834] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(44), 1,
      sym_string,
    ACTIONS(199), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(201), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [850] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(100), 1,
      sym_string,
    ACTIONS(199), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(201), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [866] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(115), 1,
      sym_string,
    ACTIONS(199), 2,
      aux_sym_string_token1,
      aux_sym_string_token2,
    ACTIONS(201), 3,
      aux_sym_string_token3,
      aux_sym_string_token4,
      aux_sym_string_token5,
  [882] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_flag,
    ACTIONS(179), 1,
      anon_sym_item,
    STATE(86), 1,
      sym_ovl_cond,
    STATE(84), 2,
      sym_ovl_flag_status,
      sym_ovl_item_presence,
  [899] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_flag,
    ACTIONS(179), 1,
      anon_sym_item,
    STATE(104), 1,
      sym_ovl_cond,
    STATE(84), 2,
      sym_ovl_flag_status,
      sym_ovl_item_presence,
  [916] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 4,
      anon_sym_RBRACE,
      anon_sym_required_items,
      anon_sym_required_flags,
      anon_sym_barred,
  [926] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 4,
      anon_sym_RBRACE,
      anon_sym_required_items,
      anon_sym_required_flags,
      anon_sym_barred,
  [936] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym_identifier,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(61), 2,
      sym_item_stmt,
      aux_sym_item_block_repeat1,
  [950] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(62), 2,
      sym_npc_stmt,
      aux_sym_npc_block_repeat1,
  [964] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    STATE(65), 2,
      sym_trigger_stmt,
      aux_sym_trigger_block_repeat1,
  [978] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    STATE(63), 2,
      sym_goal_stmt,
      aux_sym_goal_block_repeat1,
  [992] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym_identifier,
    ACTIONS(229), 1,
      anon_sym_RBRACE,
    STATE(67), 2,
      sym_spinner_stmt,
      aux_sym_spinner_block_repeat1,
  [1006] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_identifier,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(60), 2,
      sym_item_stmt,
      aux_sym_item_block_repeat1,
  [1020] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 1,
      sym_identifier,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    STATE(60), 2,
      sym_item_stmt,
      aux_sym_item_block_repeat1,
  [1034] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      sym_identifier,
    ACTIONS(241), 1,
      anon_sym_RBRACE,
    STATE(62), 2,
      sym_npc_stmt,
      aux_sym_npc_block_repeat1,
  [1048] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 1,
      sym_identifier,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
    STATE(69), 2,
      sym_goal_stmt,
      aux_sym_goal_block_repeat1,
  [1062] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 4,
      anon_sym_RBRACE,
      anon_sym_required_items,
      anon_sym_required_flags,
      anon_sym_barred,
  [1072] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      sym_identifier,
    ACTIONS(250), 1,
      anon_sym_RBRACE,
    STATE(65), 2,
      sym_trigger_stmt,
      aux_sym_trigger_block_repeat1,
  [1086] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
    STATE(56), 2,
      sym_npc_stmt,
      aux_sym_npc_block_repeat1,
  [1100] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_identifier,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
    STATE(67), 2,
      sym_spinner_stmt,
      aux_sym_spinner_block_repeat1,
  [1114] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      sym_identifier,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
    STATE(59), 2,
      sym_spinner_stmt,
      aux_sym_spinner_block_repeat1,
  [1128] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym_identifier,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    STATE(69), 2,
      sym_goal_stmt,
      aux_sym_goal_block_repeat1,
  [1142] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 4,
      anon_sym_RBRACE,
      anon_sym_required_items,
      anon_sym_required_flags,
      anon_sym_barred,
  [1152] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 4,
      anon_sym_RBRACE,
      anon_sym_required_items,
      anon_sym_required_flags,
      anon_sym_barred,
  [1162] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 4,
      anon_sym_RBRACE,
      anon_sym_required_items,
      anon_sym_required_flags,
      anon_sym_barred,
  [1172] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
    STATE(57), 2,
      sym_trigger_stmt,
      aux_sym_trigger_block_repeat1,
  [1186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 3,
      anon_sym_set,
      anon_sym_unset,
      anon_sym_complete,
  [1195] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_ovl_cond_list_repeat1,
  [1208] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    ACTIONS(283), 1,
      anon_sym_RPAREN,
    STATE(75), 1,
      aux_sym_ovl_cond_list_repeat1,
  [1221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1239] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_set_list_repeat1,
  [1252] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_COMMA,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_required_items_stmt_repeat1,
  [1265] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
    STATE(85), 1,
      aux_sym_required_flags_stmt_repeat1,
  [1278] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_COMMA,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_set_list_repeat1,
  [1291] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_COMMA,
    ACTIONS(306), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_required_items_stmt_repeat1,
  [1304] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1313] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_COMMA,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_required_flags_stmt_repeat1,
  [1326] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    ACTIONS(312), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_ovl_cond_list_repeat1,
  [1339] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_COMMA,
    ACTIONS(317), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_required_items_stmt_repeat1,
  [1352] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym_set_list_repeat1,
  [1365] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(34), 1,
      sym_boolean,
    ACTIONS(321), 2,
      anon_sym_true,
      anon_sym_false,
  [1376] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(326), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_required_flags_stmt_repeat1,
  [1389] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1405] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1413] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym_identifier,
    ACTIONS(334), 1,
      anon_sym_RBRACE,
  [1423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_room_block,
  [1433] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_item_block,
  [1443] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(340), 1,
      sym_identifier,
    ACTIONS(342), 1,
      anon_sym_RBRACE,
  [1453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(344), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_npc_block,
  [1463] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(346), 1,
      sym_identifier,
    ACTIONS(348), 1,
      anon_sym_RBRACE,
  [1473] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(350), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_trigger_block,
  [1483] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(352), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_spinner_block,
  [1493] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(354), 1,
      sym_identifier,
    ACTIONS(356), 1,
      anon_sym_RBRACE,
  [1503] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(358), 1,
      anon_sym_LBRACE,
    STATE(30), 1,
      sym_goal_block,
  [1513] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1521] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(360), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_set_list,
  [1531] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(362), 1,
      sym_identifier,
    ACTIONS(364), 1,
      anon_sym_RBRACE,
  [1541] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(366), 2,
      anon_sym_present,
      anon_sym_absent,
  [1549] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(368), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      sym_ovl_block,
  [1559] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(370), 1,
      anon_sym_text,
    STATE(112), 1,
      sym_ovl_text_stmt,
  [1569] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(372), 1,
      sym_identifier,
  [1576] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(374), 1,
      anon_sym_LBRACE,
  [1583] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(376), 1,
      anon_sym_RBRACE,
  [1590] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(378), 1,
      anon_sym_LBRACE,
  [1597] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(380), 1,
      sym_identifier,
  [1604] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(382), 1,
      anon_sym_RBRACE,
  [1611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(384), 1,
      anon_sym_LPAREN,
  [1618] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(386), 1,
      sym_identifier,
  [1625] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(388), 1,
      sym_identifier,
  [1632] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(390), 1,
      sym_identifier,
  [1639] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(392), 1,
      anon_sym_set,
  [1646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(394), 1,
      anon_sym_EQ,
  [1653] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(396), 1,
      anon_sym_LPAREN,
  [1660] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(398), 1,
      anon_sym_DASH_GT,
  [1667] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(400), 1,
      sym_identifier,
  [1674] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(402), 1,
      anon_sym_LBRACE,
  [1681] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(404), 1,
      sym_identifier,
  [1688] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(406), 1,
      sym_identifier,
  [1695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(408), 1,
      sym_identifier,
  [1702] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(410), 1,
      sym_identifier,
  [1709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(412), 1,
      sym_identifier,
  [1716] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(414), 1,
      sym_identifier,
  [1723] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(416), 1,
      ts_builtin_sym_end,
  [1730] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(418), 1,
      anon_sym_if,
  [1737] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(420), 1,
      sym_identifier,
  [1744] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(422), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 76,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 148,
  [SMALL_STATE(7)] = 184,
  [SMALL_STATE(8)] = 204,
  [SMALL_STATE(9)] = 225,
  [SMALL_STATE(10)] = 250,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 300,
  [SMALL_STATE(13)] = 314,
  [SMALL_STATE(14)] = 328,
  [SMALL_STATE(15)] = 342,
  [SMALL_STATE(16)] = 356,
  [SMALL_STATE(17)] = 370,
  [SMALL_STATE(18)] = 384,
  [SMALL_STATE(19)] = 398,
  [SMALL_STATE(20)] = 412,
  [SMALL_STATE(21)] = 426,
  [SMALL_STATE(22)] = 440,
  [SMALL_STATE(23)] = 454,
  [SMALL_STATE(24)] = 468,
  [SMALL_STATE(25)] = 482,
  [SMALL_STATE(26)] = 496,
  [SMALL_STATE(27)] = 510,
  [SMALL_STATE(28)] = 524,
  [SMALL_STATE(29)] = 538,
  [SMALL_STATE(30)] = 552,
  [SMALL_STATE(31)] = 566,
  [SMALL_STATE(32)] = 580,
  [SMALL_STATE(33)] = 594,
  [SMALL_STATE(34)] = 609,
  [SMALL_STATE(35)] = 624,
  [SMALL_STATE(36)] = 639,
  [SMALL_STATE(37)] = 654,
  [SMALL_STATE(38)] = 669,
  [SMALL_STATE(39)] = 692,
  [SMALL_STATE(40)] = 707,
  [SMALL_STATE(41)] = 722,
  [SMALL_STATE(42)] = 737,
  [SMALL_STATE(43)] = 752,
  [SMALL_STATE(44)] = 771,
  [SMALL_STATE(45)] = 786,
  [SMALL_STATE(46)] = 802,
  [SMALL_STATE(47)] = 818,
  [SMALL_STATE(48)] = 834,
  [SMALL_STATE(49)] = 850,
  [SMALL_STATE(50)] = 866,
  [SMALL_STATE(51)] = 882,
  [SMALL_STATE(52)] = 899,
  [SMALL_STATE(53)] = 916,
  [SMALL_STATE(54)] = 926,
  [SMALL_STATE(55)] = 936,
  [SMALL_STATE(56)] = 950,
  [SMALL_STATE(57)] = 964,
  [SMALL_STATE(58)] = 978,
  [SMALL_STATE(59)] = 992,
  [SMALL_STATE(60)] = 1006,
  [SMALL_STATE(61)] = 1020,
  [SMALL_STATE(62)] = 1034,
  [SMALL_STATE(63)] = 1048,
  [SMALL_STATE(64)] = 1062,
  [SMALL_STATE(65)] = 1072,
  [SMALL_STATE(66)] = 1086,
  [SMALL_STATE(67)] = 1100,
  [SMALL_STATE(68)] = 1114,
  [SMALL_STATE(69)] = 1128,
  [SMALL_STATE(70)] = 1142,
  [SMALL_STATE(71)] = 1152,
  [SMALL_STATE(72)] = 1162,
  [SMALL_STATE(73)] = 1172,
  [SMALL_STATE(74)] = 1186,
  [SMALL_STATE(75)] = 1195,
  [SMALL_STATE(76)] = 1208,
  [SMALL_STATE(77)] = 1221,
  [SMALL_STATE(78)] = 1230,
  [SMALL_STATE(79)] = 1239,
  [SMALL_STATE(80)] = 1252,
  [SMALL_STATE(81)] = 1265,
  [SMALL_STATE(82)] = 1278,
  [SMALL_STATE(83)] = 1291,
  [SMALL_STATE(84)] = 1304,
  [SMALL_STATE(85)] = 1313,
  [SMALL_STATE(86)] = 1326,
  [SMALL_STATE(87)] = 1339,
  [SMALL_STATE(88)] = 1352,
  [SMALL_STATE(89)] = 1365,
  [SMALL_STATE(90)] = 1376,
  [SMALL_STATE(91)] = 1389,
  [SMALL_STATE(92)] = 1397,
  [SMALL_STATE(93)] = 1405,
  [SMALL_STATE(94)] = 1413,
  [SMALL_STATE(95)] = 1423,
  [SMALL_STATE(96)] = 1433,
  [SMALL_STATE(97)] = 1443,
  [SMALL_STATE(98)] = 1453,
  [SMALL_STATE(99)] = 1463,
  [SMALL_STATE(100)] = 1473,
  [SMALL_STATE(101)] = 1483,
  [SMALL_STATE(102)] = 1493,
  [SMALL_STATE(103)] = 1503,
  [SMALL_STATE(104)] = 1513,
  [SMALL_STATE(105)] = 1521,
  [SMALL_STATE(106)] = 1531,
  [SMALL_STATE(107)] = 1541,
  [SMALL_STATE(108)] = 1549,
  [SMALL_STATE(109)] = 1559,
  [SMALL_STATE(110)] = 1569,
  [SMALL_STATE(111)] = 1576,
  [SMALL_STATE(112)] = 1583,
  [SMALL_STATE(113)] = 1590,
  [SMALL_STATE(114)] = 1597,
  [SMALL_STATE(115)] = 1604,
  [SMALL_STATE(116)] = 1611,
  [SMALL_STATE(117)] = 1618,
  [SMALL_STATE(118)] = 1625,
  [SMALL_STATE(119)] = 1632,
  [SMALL_STATE(120)] = 1639,
  [SMALL_STATE(121)] = 1646,
  [SMALL_STATE(122)] = 1653,
  [SMALL_STATE(123)] = 1660,
  [SMALL_STATE(124)] = 1667,
  [SMALL_STATE(125)] = 1674,
  [SMALL_STATE(126)] = 1681,
  [SMALL_STATE(127)] = 1688,
  [SMALL_STATE(128)] = 1695,
  [SMALL_STATE(129)] = 1702,
  [SMALL_STATE(130)] = 1709,
  [SMALL_STATE(131)] = 1716,
  [SMALL_STATE(132)] = 1723,
  [SMALL_STATE(133)] = 1730,
  [SMALL_STATE(134)] = 1737,
  [SMALL_STATE(135)] = 1744,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(129),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(130),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(131),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_room_block_repeat1, 2, 0, 0), SHIFT_REPEAT(133),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_exit, 4, 0, 10),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_exit, 4, 0, 10),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_exit_block_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exit_block_repeat1, 2, 0, 0), SHIFT_REPEAT(116),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exit_block_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_exit_block_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_list, 4, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_block, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_block, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_block, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spinner_block, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_block, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_decl, 5, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_block, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_def, 3, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_block, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_block, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_block, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spinner_block, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_block, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_list, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_def, 3, 0, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_def, 3, 0, 4),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spinner_def, 3, 0, 5),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_def, 3, 0, 6),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_block, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_def, 3, 0, 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_name, 2, 0, 7),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_name, 2, 0, 7),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_visited, 2, 0, 9),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_visited, 2, 0, 9),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_overlay_stmt, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_overlay_stmt, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_exit, 5, 0, 10),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_exit, 5, 0, 10),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_stmt, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_stmt, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exit_block, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exit_block, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exit_block, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exit_block, 3, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ovl_block, 3, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ovl_block, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_room_desc, 2, 0, 8),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_room_desc, 2, 0, 8),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_barred_stmt, 2, 0, 14),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_required_flags_stmt, 5, 0, 20),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [231] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_item_block_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_block_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [238] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_npc_block_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_npc_block_repeat1, 2, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exit_stmt, 1, 0, 0),
  [247] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_trigger_block_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_trigger_block_repeat1, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_spinner_block_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_spinner_block_repeat1, 2, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [261] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_goal_block_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_goal_block_repeat1, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_required_items_stmt, 4, 0, 12),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_required_flags_stmt, 4, 0, 15),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_required_items_stmt, 5, 0, 17),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ovl_cond_list_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ovl_cond_list_repeat1, 2, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ovl_flag_status, 3, 0, 11),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ovl_item_presence, 3, 0, 12),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [301] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_set_list_repeat1, 2, 0, 0), SHIFT_REPEAT(128),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_set_list_repeat1, 2, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ovl_cond, 1, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [314] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_required_items_stmt_repeat1, 2, 0, 18), SHIFT_REPEAT(124),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_required_items_stmt_repeat1, 2, 0, 18),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [323] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_required_flags_stmt_repeat1, 2, 0, 21), SHIFT_REPEAT(127),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_required_flags_stmt_repeat1, 2, 0, 21),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_required_flags_stmt_repeat1, 2, 0, 19),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_required_items_stmt_repeat1, 2, 0, 16),
  [332] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_item_stmt, 1, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_stmt, 1, 0, 0),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [340] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_npc_stmt, 1, 0, 0),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_npc_stmt, 1, 0, 0),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [346] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger_stmt, 1, 0, 0),
  [348] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger_stmt, 1, 0, 0),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [354] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_spinner_stmt, 1, 0, 0),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_spinner_stmt, 1, 0, 0),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [362] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_goal_stmt, 1, 0, 0),
  [364] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goal_stmt, 1, 0, 0),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [372] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [374] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ovl_cond_list, 3, 0, 0),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [378] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ovl_cond_list, 4, 0, 0),
  [380] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [382] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ovl_text_stmt, 2, 0, 13),
  [384] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [386] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [388] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [390] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [398] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [400] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [402] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ovl_cond_list, 1, 0, 0),
  [404] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [406] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [408] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [410] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [412] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [414] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [416] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [420] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [422] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_amble(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "amble",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
